apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: devops-lab
data:
  SPRING_PROFILES_ACTIVE: "postgres"
  database: "postgres"
  POSTGRES_URL: "jdbc:postgresql://postgres-service.devops-lab.svc.cluster.local:5432/petclinic"
