apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
type: Opaque
stringData:
  DB_PASSWORD: "tu-password-seguro-devops"