apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-backend
  namespace: devops-lab
  labels:
    app: petclinic
    component: backend
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
  minReadySeconds: 10
  selector:
    matchLabels:
      app: petclinic
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: petclinic
        component: backend
        version: "IMAGE_TAG"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: backend
        image: ghcr.io/guytho1996/spring-petclinic-devops:IMAGE_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "25m"
            memory: "256Mi"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: petclinic-config
        - secretRef:
            name: petclinic-secrets
