apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: petclinic-frontend-pdb
  namespace: devops-lab
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: petclinic
      component: frontend
