apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-frontend
  namespace: devops-lab
  labels:
    app: petclinic
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
      component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: petclinic
        component: frontend
        version: "IMAGE_TAG"
    spec:
      containers:
      - name: frontend
        image: ghcr.io/guytho1996/spring-petclinic-devops-frontend:IMAGE_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: FRONTEND_GIT_SHA
          value: "IMAGE_TAG"
        envFrom:
        - configMapRef:
            name: petclinic-config
