apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-root-redirect
  namespace: devops-lab
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://petclinic.local/grafana/dashboards
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - petclinic.local
    secretName: petclinic-frontend-tls
  rules:
  - host: petclinic.local
    http:
      paths:
      - path: /grafana
        pathType: Exact
        backend:
          service:
            name: grafana
            port:
              number: 3000
      - path: /grafana/
        pathType: Exact
        backend:
          service:
            name: grafana
            port:
              number: 3000
