apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-metrics-ingress
  namespace: devops-lab
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Allow external Prometheus server IP and internal cluster networks (SNAT)
    nginx.ingress.kubernetes.io/whitelist-source-range: "129.159.70.134,10.42.0.0/16,10.43.0.0/16,10.0.0.0/8"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - guytho1996-petclinic.eastus2.cloudapp.azure.com
    secretName: petclinic-frontend-tls
  rules:
  - host: guytho1996-petclinic.eastus2.cloudapp.azure.com
    http:
      paths:
      - path: /actuator/prometheus
        pathType: Prefix
        backend:
          service:
            name: petclinic-backend
            port:
              number: 8080
