apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: devops-lab
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - guytho1996-petclinic.eastus2.cloudapp.azure.com
    secretName: petclinic-frontend-tls
  rules:
  - host: guytho1996-petclinic.eastus2.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-frontend
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: external-grafana-service
            port:
              number: 3000
