spring.application.name=spring-petclinic-devops
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

management.tracing.enabled=true
management.tracing.sampling.probability=1.0

logging.pattern.level=%5p [${spring.application.name:petclinic},%X{traceId:-},%X{spanId:-}]

management.endpoint.health.show-details=always
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
management.metrics.enable.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Configuración de conexión a PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.ltbiaasgerlajqujhdop&password=POp85n3q5RNtggSa

# Configuración del driver (Spring Boot lo detecta automáticamente)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Para que cree las tablas automáticamente al iniciar)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Puerto
