name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: spring-petclinic-repo-dev

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Configurar la conexión al clúster (Se usa un secreto de GitHub)
      - name: Set up Kubernetes Configuration
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      # Ejecutar el Rolling Update con la nueva imagen
      - name: Deploy to Kubernetes
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Iniciando Rolling Update en el clúster..."
          kubectl set image deployment/spring-petclinic petclinic-app=$REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          kubectl rollout status deployment/spring-petclinic